/**
 * mt5sync.js — MT5 Sync UI for the Trade Journal frontend
 */

let syncHistory = [];
let autoSyncInterval = null;

function renderMT5SyncSection() {
  const container = document.getElementById('mt5SyncContainer');
  if (!container) return;

  container.innerHTML = `
    <div class="sync-status-card" id="syncStatusCard">
      <div class="sync-status-indicator">
        <div class="sync-dot sync-dot-unknown" id="syncDot"></div>
        <div>
          <div class="sync-status-label" id="syncStatusLabel">Checking status…</div>
          <div class="sync-status-meta" id="syncStatusMeta"></div>
        </div>
      </div>
      <div class="sync-actions">
        <label class="sync-toggle-label">
          <input type="checkbox" id="autoSyncToggle"> Auto-sync (every <span id="syncIntervalLabel">30</span>s)
        </label>
        <button class="btn btn-primary" onclick="syncNow()">🔄 Sync Now</button>
      </div>
    </div>

    <div class="sync-stats-grid" id="syncStatsGrid">
      <div class="stat-card">
        <div class="card-label">MT5 Trades in DB</div>
        <div class="card-value" id="mt5TradeCount">—</div>
      </div>
      <div class="stat-card">
        <div class="card-label">Last Sync</div>
        <div class="card-value" id="lastSyncTime" style="font-size:14px;">—</div>
      </div>
      <div class="stat-card">
        <div class="card-label">New (last sync)</div>
        <div class="card-value positive" id="lastSyncNew">—</div>
      </div>
      <div class="stat-card">
        <div class="card-label">Updated (last sync)</div>
        <div class="card-value" id="lastSyncUpdated">—</div>
      </div>
    </div>

    <div class="file-path-section">
      <h3>📁 MT5 Export File Path</h3>
      <p style="color:var(--text-secondary);font-size:13px;margin-bottom:12px;">
        Enter the full path to the <code>mt5_trades.json</code> file generated by the TradeExporter EA.
        Typically found in: <code>%APPDATA%\\MetaQuotes\\Terminal\\[ID]\\MQL5\\Files\\mt5_trades.json</code>
      </p>
      <div style="display:flex;gap:8px;align-items:center;">
        <input type="text" id="mt5FilePathInput" class="form-input" placeholder="C:\\Users\\...\\mt5_trades.json" style="flex:1;">
        <button class="btn btn-primary" onclick="saveFilePath()">Save</button>
      </div>
    </div>

    <div class="mt5-instructions">
      <h3>📋 EA Installation Instructions</h3>
      <ol>
        <li>Open MetaTrader 5 and press <code>Ctrl+N</code> to open the Navigator panel.</li>
        <li>Go to <strong>File → Open Data Folder</strong>.</li>
        <li>Copy <code>TradeExporter.mq5</code> to the <code>MQL5\\Experts\\</code> folder.</li>
        <li>Back in MT5 Navigator, right-click <strong>Expert Advisors → Refresh</strong>.</li>
        <li>Drag the <code>TradeExporter</code> EA onto any chart.</li>
        <li>In the EA settings, enable <strong>Allow DLL imports</strong> and <strong>Allow algo trading</strong>.</li>
        <li>Press <strong>OK</strong> — the EA will export trades every 5 seconds to <code>MQL5\\Files\\mt5_trades.json</code>.</li>
        <li>Copy the full path to that file and paste it in the field above, then click <strong>Save</strong>.</li>
        <li>Click <strong>Sync Now</strong> to import your trades.</li>
      </ol>
    </div>

    <div class="sync-log-section">
      <h3>📜 Sync History</h3>
      <div id="syncLogContainer">
        <p style="color:var(--text-secondary);font-size:13px;">No sync history yet.</p>
      </div>
    </div>
  `;

  // Populate file path from settings
  const filePathInput = document.getElementById('mt5FilePathInput');
  if (filePathInput && settings.mt5_file_path) {
    filePathInput.value = settings.mt5_file_path;
  }

  // Auto-sync toggle
  const autoSyncToggle = document.getElementById('autoSyncToggle');
  if (autoSyncToggle) {
    autoSyncToggle.checked = settings.auto_sync === 'true';
    const syncInterval = parseInt(settings.sync_interval || '30', 10);
    const intervalLabel = document.getElementById('syncIntervalLabel');
    if (intervalLabel) intervalLabel.textContent = syncInterval;
    autoSyncToggle.addEventListener('change', toggleAutoSync);
  }

  loadSyncStatus();
}

async function loadSyncStatus() {
  try {
    const status = await fetch(`${API_BASE}/api/sync/status`).then(r => r.json());
    renderSyncStatus(status);
  } catch (e) {
    const label = document.getElementById('syncStatusLabel');
    const dot = document.getElementById('syncDot');
    if (label) label.textContent = 'Cannot reach backend server';
    if (dot) { dot.className = 'sync-dot sync-dot-disconnected'; }
  }
}

function renderSyncStatus(status) {
  const dot = document.getElementById('syncDot');
  const label = document.getElementById('syncStatusLabel');
  const meta = document.getElementById('syncStatusMeta');
  const tradeCount = document.getElementById('mt5TradeCount');
  const lastSync = document.getElementById('lastSyncTime');
  const lastNew = document.getElementById('lastSyncNew');
  const lastUpdated = document.getElementById('lastSyncUpdated');

  const isConnected = status.status === 'connected';

  if (dot) {
    dot.className = 'sync-dot ' + (isConnected ? 'sync-dot-connected' : 'sync-dot-disconnected');
  }
  if (label) {
    label.textContent = isConnected ? '✅ MT5 File Connected' : '❌ MT5 File Not Found';
  }
  if (meta) {
    meta.textContent = status.file_path || 'No file path configured';
  }
  if (tradeCount) {
    tradeCount.textContent = status.mt5_trade_count !== undefined ? status.mt5_trade_count : '—';
  }
  if (lastSync) {
    if (status.last_sync_time) {
      try {
        lastSync.textContent = new Date(status.last_sync_time).toLocaleString();
      } catch { lastSync.textContent = status.last_sync_time; }
    } else {
      lastSync.textContent = 'Never';
    }
  }
  if (lastNew && status.last_sync_result) {
    lastNew.textContent = status.last_sync_result.new ?? 0;
  } else if (lastNew) {
    lastNew.textContent = '—';
  }
  if (lastUpdated && status.last_sync_result) {
    lastUpdated.textContent = status.last_sync_result.updated ?? 0;
  } else if (lastUpdated) {
    lastUpdated.textContent = '—';
  }
}

async function syncNow() {
  showToast('Syncing trades from MT5 file…', 'info');
  try {
    const result = await fetch(`${API_BASE}/api/sync`, { method: 'POST' }).then(async r => {
      if (!r.ok) {
        const err = await r.json().catch(() => ({}));
        throw new Error(err.detail || r.statusText);
      }
      return r.json();
    });

    syncHistory.unshift({
      time: new Date().toLocaleString(),
      new: result.new || 0,
      updated: result.updated || 0,
      total: result.total || 0,
      errors: result.errors || 0,
    });

    renderSyncLog(syncHistory);
    await loadSyncStatus();
    await loadTrades();
    if (currentSection === 'dashboard') renderDashboard();

    showToast(`Sync complete! ${result.new} new, ${result.updated} updated.`, 'success');
  } catch (e) {
    showToast('Sync failed: ' + e.message, 'error');
  }
}

function renderSyncLog(history) {
  const container = document.getElementById('syncLogContainer');
  if (!container) return;
  if (!history.length) {
    container.innerHTML = '<p style="color:var(--text-secondary);font-size:13px;">No sync history yet.</p>';
    return;
  }
  container.innerHTML = history.slice(0, 20).map(entry => `
    <div class="sync-log-entry">
      <span class="sync-log-time">${entry.time}</span>
      <span class="sync-log-result">
        <span class="sync-log-badge-new">+${entry.new} new</span>
        &nbsp;
        <span class="sync-log-badge-updated">${entry.updated} updated</span>
        &nbsp;· ${entry.total} total
        ${entry.errors ? `<span style="color:var(--red)"> · ${entry.errors} errors</span>` : ''}
      </span>
    </div>
  `).join('');
}

async function saveFilePath() {
  const input = document.getElementById('mt5FilePathInput');
  if (!input) return;
  const path = input.value.trim();
  try {
    await fetch(`${API_BASE}/api/settings`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ mt5_file_path: path }),
    });
    settings.mt5_file_path = path;
    showToast('File path saved!', 'success');
    await loadSyncStatus();
  } catch (e) {
    showToast('Error saving path: ' + e.message, 'error');
  }
}

function toggleAutoSync() {
  const toggle = document.getElementById('autoSyncToggle');
  const enabled = toggle ? toggle.checked : false;
  settings.auto_sync = enabled ? 'true' : 'false';

  fetch(`${API_BASE}/api/settings`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ auto_sync: enabled ? 'true' : 'false' }),
  }).catch(e => console.error('Error saving auto_sync setting:', e));

  if (enabled) {
    const interval = parseInt(settings.sync_interval || '30', 10);
    setupAutoSync(interval);
    showToast(`Auto-sync enabled (every ${interval}s)`, 'success');
  } else {
    if (autoSyncInterval) { clearInterval(autoSyncInterval); autoSyncInterval = null; }
    showToast('Auto-sync disabled', 'info');
  }
}

function setupAutoSync(intervalSeconds) {
  if (autoSyncInterval) clearInterval(autoSyncInterval);
  autoSyncInterval = setInterval(async () => {
    if (settings.auto_sync !== 'true') return;
    try {
      const result = await fetch(`${API_BASE}/api/sync`, { method: 'POST' }).then(r => r.ok ? r.json() : null);
      if (result) {
        syncHistory.unshift({
          time: new Date().toLocaleString(),
          new: result.new || 0,
          updated: result.updated || 0,
          total: result.total || 0,
          errors: result.errors || 0,
        });
        if (currentSection === 'mt5sync') {
          renderSyncLog(syncHistory);
          await loadSyncStatus();
        }
        if (result.new > 0 || result.updated > 0) {
          await loadTrades();
          if (currentSection === 'dashboard') renderDashboard();
        }
      }
    } catch (e) { /* silent auto-sync error */ }
  }, intervalSeconds * 1000);
}

window.syncNow = syncNow;
window.saveFilePath = saveFilePath;
window.toggleAutoSync = toggleAutoSync;
